// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvdclmlryvhijikvjsbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2ZGNsbWxyeXZoaWppa3Zqc2JjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4ODc1MzgsImV4cCI6MjA3MzQ2MzUzOH0.-A6R_tm0_vA_8S2FW53QoIHaf-quw45IC48ShvVU_TM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});